version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: munidmdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Munidm91!!!
      MYSQL_DATABASE: munidm_db
      MYSQL_USER: munidm
      MYSQL_PASSWORD: Munidm91!!!
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pMunidm91!!!"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build: ./server
    image: abdulrahman939291/server
    container_name: server
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      MYSQL_HOST: munidmdb
      MYSQL_USER: munidm
      MYSQL_PASSWORD: Munidm91!!!
      MYSQL_DATABASE: munidm_db
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    image: abdulrahman939291/client
    container_name: client
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - server

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: munidmdb
      MYSQL_ROOT_PASSWORD: Munidm91!!!
    depends_on:
      - db

volumes:
  mysql_data: